### ISSUE TITLE
[C5][environment] Configuration API to read configurations from client

### ISSUE THREAD

**Issue by RenukaFernando** [wso2/carbon-apimgt#4696]
**Description:**
Rest API to expose configurations to client. Currently environment configurations.

- sample deployment.yaml
```yaml
wso2.carbon.apimgt:
    # Environment Configurations
  environmentConfigurations:
      # list of web clients (eg: 127.0.0.1:9292) to allow make requests to current environment
      # (use '*' to allow any web client)
    allowedHosts:
    - ui.sample.com:9292
    - dev.sample.com:9292
      # current environment's label from the list of environments
    environmentLabel: Development


  # APIM UI Configuration Parameters
wso2.carbon.apimgt.ui.configs:
    # list of environments
    #   ◆ host           - host of a environment (eg 127.0.0.1:9292, use '<empty-string>' for current host)
    #   ◆ loginTokenPath - token endpoint URL
    #   ◆ label          - environment label to uniquely identify a environment
  environments:
  - host: dev.sample.com:9292
    loginTokenPath: /login/token
    label: Development

  - host: prod.sample.com:9292
    loginTokenPath: /login/token
    label: Production
```
