### ISSUE TITLE
Custom JWTGenerator [apim.jwt.generator_imp] setting is ignored

### ISSUE THREAD

**Issue by kishiguro** [wso2/carbon-apimgt#8612]
### Description:
Even if we configure Custom JWTGenerator in [apim.jwt.generator_imp], the setting is completely ignored.

### Steps to reproduce:
Set `generator_impl` config at `repository/conf/deployment.toml`

``` toml
[apim.jwt]
enable = true
encoding = "base64"
generator_impl = "org.wso2.custom.TokenGenerator.CustomTokenGenerator"
claim_dialect = "http://wso2.org/claimsx"
header = "X-JWT-Assertion"
signing_algorithm = "SHA256withRSA"
enable_user_claims = true
claims_extractor_impl = "org.wso2.carbon.apimgt.impl.token.DefaultClaimsRetriever"
```
The CustomTokenGenerator https://github.com/Senthuran100/CustomJWTGenerator is used.  We believe somewhere between carbon-apimgt v6.5.437 and v6.6.10 this bug is introduced.

### Affected Product Version:
WSO2 API Manager 3.1.0-Alpha and after has the issue.  WSO2 API Manager 3.1.0-M5 and previous version does not have the issue. In carbon-apimgt, v6.5.437 is ok, but v6.6.10 has the issue.

### Environment details (with versions):
- OS: Mac OS 10.15.5 & Ubuntu 18.04
- Client:
- Env (Docker/K8s): Native

---
